spring:
  application:
    name: library
  datasource:
    url: "jdbc:mysql://localhost:3306/library"
    password: root
    username: root
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

server:
  port: 8080
  servlet:
    context-path: /library
